#!/usr/bin/env bash
# Summary: Explain how the current Node version is set
set -e
[ -n "$JSENV_DEBUG" ] && set -x

if [ -n "$JSENV_VERSION" ]; then
  echo "JSENV_VERSION environment variable"
else
  jsenv-version-file
fi
