#!/usr/bin/env bash
# Summary: Show the current Node version and its origin
#
# Shows the currently selected Node version and how it was
# selected. To obtain only the version string, use `jsenv version-name'.

set -e
[ -n "$JSENV_DEBUG" ] && set -x

echo "$(jsenv-version-name) (set by $(jsenv-version-origin))"
