#!/usr/bin/env bash
set -e
[ -n "$JSENV_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${JSENV_ROOT}" ]; then
  JSENV_ROOT="${HOME}/.jsenv"
else
  JSENV_ROOT="${JSENV_ROOT%/}"
fi
export JSENV_ROOT

if [ -z "${JSENV_DIR}" ]; then
  JSENV_DIR="$(pwd)"
else
  cd "$JSENV_DIR" 2>/dev/null || {
    echo "jsenv: cannot change working directory to \`$JSENV_DIR'"
    exit 1
  } >&2
  JSENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export JSENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${JSENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${JSENV_HOOK_PATH}:${JSENV_ROOT}/jsenv.d:/usr/local/etc/jsenv.d:/etc/jsenv.d:/usr/lib/jsenv/hooks"
for plugin_hook in "${JSENV_ROOT}/plugins/"*/etc/jsenv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export JSENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(jsenv---version)\n$(jsenv-help)" >&2
  ;;
"-v" )
  exec jsenv---version
  ;;
* )
  command_path="$(command -v "jsenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "jsenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
