#!/usr/bin/env bash
set -e
[ -n "$JSENV_DEBUG" ] && set -x

# Provide jsenv completions
if [ "$1" = "--complete" ]; then
  exec jsenv-rehash --complete
fi

# When jsenv shell integration is enabled, delegate to jsenv-rehash,
# then tell the shell to empty its command lookup cache.
jsenv-rehash
echo "hash -r"
