#!/usr/bin/env bash
# Summary: List existing jsenv shims
# Usage: jsenv shims [--short]

set -e
[ -n "$JSENV_DEBUG" ] && set -x

# Provide jsenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

for command in "${JSENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
