#!/usr/bin/env bash
# Summary: Display prefix for a Node version
# Usage: jsenv prefix [<version>]
#
# Displays the directory where a Node version is installed. If no
# version is given, `jsenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$JSENV_DEBUG" ] && set -x

# Provide jsenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec jsenv-versions --bare
fi

if [ -n "$1" ]; then
  export JSENV_VERSION="$1"
elif [ -z "$JSENV_VERSION" ]; then
  JSENV_VERSION="$(jsenv-version-name)"
fi

if [ "$JSENV_VERSION" = "system" ]; then
  NODE_PATH="$(jsenv-which node)"
  NODE_PATH="${NODE_PATH%/*}"
  echo "${NODE_PATH%/bin}"
  exit
fi

JSENV_PREFIX_PATH="${JSENV_ROOT}/versions/${JSENV_VERSION}"
if [ ! -d "$JSENV_PREFIX_PATH" ]; then
  echo "jsenv: version \`${JSENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$JSENV_PREFIX_PATH"
