#!/usr/bin/env bash
# Usage: jsenv completions <command> [arg1 arg2...]

set -e
[ -n "$JSENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  jsenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "jsenv-$COMMAND" || command -v "jsenv-sh-$COMMAND")"
if grep -i "^# provide jsenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
