#!/usr/bin/env bash
# Summary: Detect the file that sets the current jsenv version

set -e
[ -n "$JSENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.node-version" ]; then
      echo "${root}/.node-version"
      exit
    elif [ -e "${root}/.jsenv-version" ]; then
      echo "${root}/.jsenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$JSENV_DIR"
[ "$JSENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${JSENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${JSENV_ROOT}/global" ]; then
  echo "${JSENV_ROOT}/global"
elif [ -e "${JSENV_ROOT}/default" ]; then
  echo "${JSENV_ROOT}/default"
else
  echo "$global_version_file"
fi
